CleoUI/CleoUI/Models/Instrument.cs
using System.ComponentModel.DataAnnotations;

namespace CleoUI.Models
{
    public class Instrument
    {
        [Key]
        public int InstrumentID { get; set; }
        [Required]
        public string? InstrumentName { get; set; }
        public string? InstrumentCode { get; set; }
        public string? InstrumentURL { get; set; }

    }
}

CleoUI/CleoUI/Models/InstrumentResult.cs
using System.ComponentModel.DataAnnotations;

namespace CleoUI.Models
{
    public class InstrumentResult
    {
        [Key]
        public int ResultID { get; set; }
        [Required]
        public int InstrumentID { get; set; }
        public string? WeeklyResult { get; set; }
        public string? MonthlyResult { get; set; }
        public int Price { get; set; }
        public DateTime When { get; set; }
    }
}

CleoUI/CleoUI/Models/Result.cs
using System.ComponentModel.DataAnnotations;

namespace CleoUI.Models
{
    public class Result
    {
        [Key]
        public int ResultID { get; set; }
        [Required]
        public int InstrumentID { get; set; }
        public string? WeeklyResult { get; set; }
        public string? MonthlyResult { get; set; }
        public int Price { get; set; }
        public DateTime When { get; set; }
    }
}

CleoUI/CleoUI/Controllers/InstrumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CleoUI;
using CleoUI.Models;

namespace CleoUI.Controllers
{
    public class InstrumentsController : Controller
    {
        private readonly CleoUIDbContext _context;

        public InstrumentsController(CleoUIDbContext context)
        {
            _context = context;
        }

        // GET: Instruments
        public async Task<IActionResult> Index()
        {
              return _context.Instruments != null ? 
                          View(await _context.Instruments.ToListAsync()) :
                          Problem("Entity set 'CleoUIDbContext.Instruments'  is null.");
        }

        // GET: Instruments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Instruments == null)
            {
                return NotFound();
            }

            var instrument = await _context.Instruments
                .FirstOrDefaultAsync(m => m.InstrumentID == id);
            if (instrument == null)
            {
                return NotFound();
            }

            return View(instrument);
        }

        // GET: Instruments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Instruments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InstrumentID,InstrumentName,InstrumentCode,InstrumentURL")] Instrument instrument)
        {
            if (ModelState.IsValid)
            {
                _context.Add(instrument);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(instrument);
        }

        // GET: Instruments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Instruments == null)
            {
                return NotFound();
            }

            var instrument = await _context.Instruments.FindAsync(id);
            if (instrument == null)
            {
                return NotFound();
            }
            return View(instrument);
        }

        // POST: Instruments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InstrumentID,InstrumentName,InstrumentCode,InstrumentURL")] Instrument instrument)
        {
            if (id != instrument.InstrumentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(instrument);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstrumentExists(instrument.InstrumentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(instrument);
        }

        // GET: Instruments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Instruments == null)
            {
                return NotFound();
            }

            var instrument = await _context.Instruments
                .FirstOrDefaultAsync(m => m.InstrumentID == id);
            if (instrument == null)
            {
                return NotFound();
            }

            return View(instrument);
        }

        // POST: Instruments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Instruments == null)
            {
                return Problem("Entity set 'CleoUIDbContext.Instruments'  is null.");
            }
            var instrument = await _context.Instruments.FindAsync(id);
            if (instrument != null)
            {
                _context.Instruments.Remove(instrument);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstrumentExists(int id)
        {
          return (_context.Instruments?.Any(e => e.InstrumentID == id)).GetValueOrDefault();
        }
    }
}

CleoUI/CleoUI/Pages/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CleoUI.Pages
{
    public class DashboardModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CleoUI/CleoUI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CleoUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CleoUI/CleoUI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CleoUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

CleoUI/CleoUI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CleoUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

CleoUI/CleoUI/Pages/Dashboard.cshtml
@page
@model CleoUI.Pages.DashboardModel

@{
    ViewData["Title"] = "Dashboard";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="text-center">
    <h1 class="display-4">TEST</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <p><button class="btn btn-primary" id="load">Load</button></p>

    <div id="grid"></div>
    <div id="grid2"></div>
</div>

@section scripts{
    <script>
    </script>
}

CleoUI/CleoUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CleoUI/CleoUI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleoUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleoUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CleoUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instruments" asp-action="Index">Instruments</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CleoUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CleoUI/CleoUI/Views/Instruments/Create.cshtml
@model CleoUI.Models.Instrument

@{
    ViewData["Title"] = "Create";
}


<h4>Instrument</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InstrumentName" class="control-label"></label>
                <input asp-for="InstrumentName" class="form-control" />
                <span asp-validation-for="InstrumentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentCode" class="control-label"></label>
                <input asp-for="InstrumentCode" class="form-control" />
                <span asp-validation-for="InstrumentCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentURL" class="control-label"></label>
                <input asp-for="InstrumentURL" class="form-control" />
                <span asp-validation-for="InstrumentURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CleoUI/CleoUI/Views/Instruments/Delete.cshtml
@model CleoUI.Models.Instrument

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instrument</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InstrumentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InstrumentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InstrumentCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InstrumentCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InstrumentURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InstrumentURL)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InstrumentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

CleoUI/CleoUI/Views/Instruments/Details.cshtml
@model CleoUI.Models.Instrument

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Instrument</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InstrumentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InstrumentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InstrumentCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InstrumentCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InstrumentURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InstrumentURL)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.InstrumentID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

CleoUI/CleoUI/Views/Instruments/Edit.cshtml
@model CleoUI.Models.Instrument

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Instrument</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InstrumentID" />
            <div class="form-group">
                <label asp-for="InstrumentName" class="control-label"></label>
                <input asp-for="InstrumentName" class="form-control" />
                <span asp-validation-for="InstrumentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentCode" class="control-label"></label>
                <input asp-for="InstrumentCode" class="form-control" />
                <span asp-validation-for="InstrumentCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentURL" class="control-label"></label>
                <input asp-for="InstrumentURL" class="form-control" />
                <span asp-validation-for="InstrumentURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

CleoUI/CleoUI/Views/Instruments/Index.cshtml
@model IEnumerable<CleoUI.Models.Instrument>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InstrumentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InstrumentCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InstrumentURL)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InstrumentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InstrumentCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InstrumentURL)
            </td>

            <td>
                <div id="spinner" class="spinner col-2"></div>
                <button class="btn btn-primary" id="load" onclick="LoadInstrument('@Html.DisplayFor(modelItem => item.InstrumentURL)','@Html.DisplayFor(modelItem => item.InstrumentCode)')">Load</button>
                <div id="@Html.DisplayFor(modelItem => item.InstrumentCode)"></div>
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.InstrumentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.InstrumentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.InstrumentID">Delete</a>
            </td>

        </tr>
}
    </tbody>
</table>

<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="$('.modal').hide()">Close</button>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="~/css/custom.css" type="text/css" />

@section scripts{
    <script>
        function LoadInstrument(element, id)
        {
            var address = "http://localhost:5000/scrape/" + element;
            // Show the spinner
            $('#spinner').show();

            $.get(address, function (data) {
                
                var weekly = data['weekly'];
                var monthly = data['monthly'];
                $('#' + id).html("Weekly: " + weekly + " " + "Monthly: " + monthly);
                $('#spinner').hide();
            });

            
        }
    </script>
    }

CleoUI/CleoUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleoUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleoUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CleoUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instruments" asp-action="Index">Instruments</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CleoUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>